using Application.Contracts;
using Infrastructure.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace WebApi.Controllers;

[Route("api/auth")]
[ApiController]
public class AuthController : ControllerBase
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly IAuthorizeResultService _authorizeResultService;
    private readonly ICodeStoreService _codeStoreService;
    private readonly IUserService _userService;

    public AuthController(IHttpContextAccessor httpContextAccessor,
        IAuthorizeResultService authorizeResultService,
        ICodeStoreService codeStoreService,
        IUserService userService)
    {
        _httpContextAccessor = httpContextAccessor;
        _authorizeResultService = authorizeResultService;
        _codeStoreService = codeStoreService;
        _userService = userService;
    }

    [HttpPost("login")]
    public async Task<IActionResult> Login(OpenIdConnectLoginRequest loginRequest)
    {
        if (!loginRequest.IsValid())
        {
            return Redirect("/error");
        }

        var loginResult = await _userService.LoginAsync(loginRequest);

        if (loginResult.Succeeded)
        {
            var result = _codeStoreService.UpdatedClientDataByCode(loginRequest.Code, loginResult.ClaimsPrincipal, loginRequest.RequestedScopes);

            if (result != null)
            {
                loginRequest.RedirectUri = loginRequest.RedirectUri + "&code=" + loginRequest.Code;
                return Redirect(loginRequest.RedirectUri);
            }
        }

        return Redirect("error");
    }

    /// <summary>
    /// Authorization endpoint
    /// </summary>
    /// <param name="response_type">Response Type, is required</param>
    /// <param name="client_id">Client Id, is required</param>
    /// <param name="redirect_uri">Redirect Uri, is optional. The redirection endpoint URI MUST be an absolute URI as defined by [RFC3986] Section 4.3</param>
    /// <param name="scope">Optional</param>
    /// <param name="state">Return the state in the result if it was present in the client authorization request</param>
    /// <param name="nonce">This is generated by the client and the authorization server must return it to client after generating the identity_token</param>
    /// <param name="code_challenge">If is null so the clinet use Rkce</param>
    /// <param name="code_challenge_method">Hasher type for <see cref="code_challenge"/></param>
    /// <returns></returns>
    [HttpGet("authorize")]
    public IActionResult Authorize(
        [FromQuery] string response_type,
        [FromQuery] string client_id,
        [FromQuery] string redirect_uri,
        [FromQuery] string scope,
        [FromQuery] string state,
        [FromQuery] string nonce,
        [FromQuery] string code_challenge,
        [FromQuery] string code_challenge_method)
    {
        var authorizationRequest = new AuthorizationRequest
        {
            response_type = response_type,
            client_id = client_id,
            redirect_uri = redirect_uri,
            scope = scope,
            state = state,
            nonce = nonce,
            code_challenge = code_challenge,
            code_challenge_method = code_challenge_method
        };

        var result = _authorizeResultService.AuthorizeRequest(_httpContextAccessor, authorizationRequest);

        if (result.HasError)
        {
            return Redirect("/error");
        }

        if (_httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
        {
            var updateCodeResult = _codeStoreService.UpdatedClientDataByCode(result.Code,
                    _httpContextAccessor.HttpContext.User, result.RequestedScopes);

            if (updateCodeResult != null)
            {
                result.RedirectUri = result.RedirectUri + "&code=" + result.Code;
                return Redirect(result.RedirectUri);
            }
            else
            {
                return Redirect("/error");
            }
        }

        return Redirect($"/login?redirect_uri={result.RedirectUri}&code={result.Code}&requested_scopes={result.RequestedScopes}");
    }
}
